### ISSUE TITLE
Item Icon are Black using shaders

### ISSUE THREAD

**Issue by NoxXVI** [Sjouwer/gamma-utils#1]
When I turn on shaders all the items are now black blocks.
![2021-07-18_10 17 50](https://user-images.githubusercontent.com/77456834/126060636-753ada02-cfb1-4dbf-8b29-378b5929105c.png)
Same when the gamma is on 100% mode

**Comment by Sjouwer** [comment]
This is an issue with optifine and not with this mod.
This mod doesn't change anything that could cause an issue like that.
When the gamma is set to 100% it'll be exactly the same as having your brightness setting on 'bright' without this mod.
It seems like the latest optfine fixes some issues related to shaders, so make sure to update it.
Also keep in mind this mod won't work with shaders anyway.
