### ISSUE TITLE
[Feature Request] More Hotkeys

### ISSUE THREAD

**Issue by GhostIsBeHere** [Sjouwer/gamma-utils#11]
I'd like to be able to set extra hotkeys that would toggle gamma at different percentages.

**Comment by Sjouwer** [comment]
Hmm, that should be pretty easy to add, how many do you need though?

**Comment by Sjouwer** [comment]
I'm really sorry about the closing & opening.
GitHub acts a bit weird on mobile

**Comment by GhostIsBeHere** [comment]
No problem about the closing/reopening. Three hot keys should be good, but more wouldn't hurt.
Thank you!

**Comment by Sjouwer** [comment]
I'm sorry that it's taking so long. I've been incredible busy with other things these past weeks. I was also hoping to wait till 1.19.1, to see if anything breaks again, though that seems to be taking longer than expected to release.

I was thinking though, this mod already supports commands and you could set as many toggles as you like with a macro mod and the `/gamma set <value>` command. Which should at least solve the problem till I actually make a new release

**Comment by Sjouwer** [comment]
I know it's not exactly what you requested, however I added 2 more keybinds:
- Max Gamma keybind (uses `Maximum Gamma Limit` in the config)
- Min Gamma keybind (uses `Minimum Gamma Limit` in the config)

If you disable `Limit Check` in the config, you can pretty much use them as extra gamma keybinds
If more keybinds are needed I'd recommend using a macro mod as mentioned in my reply above

**Comment by GhostIsBeHere** [comment]
That will work great. Thank you!
