### ISSUE TITLE
Night Vision Toggle stuck

### ISSUE THREAD

**Issue by GeardoGrunt** [Sjouwer/gamma-utils#13]
The night vision toggle simply isn't working for me. 
To put it simply: every time I click on the key it says it's enabled.
Doesn't seem to be able to deactivate for some reason.

**Comment by Sjouwer** [comment]
I never ran into an issue like that, would you be able to provide a bit more info:
Which minecraft version are you playing?
Which Gamma Utils version did you install?
Which other mods do you have installed?
Are you using another launcher than the vanilla one?

**Comment by GeardoGrunt** [comment]
Sorry about the lack of info, my bad.
1.19.2
Gamma utils 1.6.10
Using MultiMC
Many, many mods:
[mods.txt](https://github.com/Sjouwer/gamma-utils/files/9429258/mods.txt)

**Comment by Sjouwer** [comment]
Thank you for the extra info
I suspect there might be a conflict with another mod
I'll have to figure that one out, I'll get back to you asap

**Comment by Sjouwer** [comment]
Btw, does this always happen, or only on a server?

**Comment by GeardoGrunt** [comment]
> 

Just tested it out, the same thing in SP. 
Don't stress too much about it bro, Sunday I'll probably remove mod by mod and see which one it is.

**Comment by GeardoGrunt** [comment]
Just tested it out, the same thing in SP.
Don't stress too much about it bro, Sunday I'll probably remove mod by mod and see which one it is.

**Comment by Sjouwer** [comment]
Thank you, that would be very helpful. It's probably easiest to first run Gamma Utils with only Fabric API and Cloth Config, to make sure it's actually a mod conflict issue or not.

**Comment by GeardoGrunt** [comment]
Good news!! I've updated all the mods and it seems to have fixed it!! Thanks a lot for your attention man! You're awesome! Keep up the good work!

**Comment by Sjouwer** [comment]
Awesome, that's great to hear!
Thank you too for reporting about the issue and keeping me up to date.
