### ISSUE TITLE
No binding for Night vision toggle

### ISSUE THREAD

**Issue by Moestchen** [Sjouwer/gamma-utils#14]
i have other mods that use the letter H as a secondary key, on newer versions of this mod my game looks like a disco party lmao. please add a keybind or a way to disable the night vision toggle!

**Comment by Sjouwer** [comment]
It's already possible to change the Night Vision keybind:
Options -> Controls -> Key Binds

![image](https://user-images.githubusercontent.com/84018133/186867543-cbdf1cf2-0215-435f-a67e-f5942141a7b6.png)
