### ISSUE TITLE
Cant disable "Show Status Effect"

### ISSUE THREAD

**Issue by Hoogmag** [Sjouwer/gamma-utils#16]
I enabled "Show Status Effect" but now i cant disbale it anymore. I use v1.6.10 and Minecraft version 1.19.2. Im using these Mods:
![Bild_2022-10-30_172058449](https://user-images.githubusercontent.com/108354933/198889661-c2f1f197-d7d2-4619-bdee-a45accfc57c1.png)
![image](https://user-images.githubusercontent.com/108354933/198889670-f581e73d-ea16-41c7-b09d-4d32244ca926.png)
![image](https://user-images.githubusercontent.com/108354933/198889683-0e157aeb-ace9-4d4b-b8c2-48bde28e7045.png)

**Comment by Sjouwer** [comment]
What exactly do you mean with you can't disable it anymore?
Do you mean the option won't save when you change it or that even if it's disabled in options that it still shows?
Also which Status Effect is the problem? The Night Vision status effect will always show if you enable night vision.
The Show Status Effect option is only for tthe Gamma toggle

**Comment by Sjouwer** [comment]
I'll be closing this now since there hasn't been a reply in almost 2 months.
I've done some testing and I wasn't able to produce any results that aren't intended.
Feel free to create a new issue if you can provide more information.
