### ISSUE TITLE
Old Potion Colors incompatibility

### ISSUE THREAD

**Issue by Felix14-v2** [Sjouwer/gamma-utils#21]
Minecraft crashes after getting an effect with the gamma status effect enabled 

# Info:
- Fabric Loader 0.14.18
- Fabric API 0.76.0
- [Old Potions](https://github.com/Abbie5/oldpotions) 2.1
- Gamma Utils 1.6.14
- (+ StackDeobfuscator 1.2.0 and Shared Resources 1.5.0)

# Related
[latest.log](https://github.com/Abbie5/oldpotions/files/11056218/latest.log)
[oldpotions#4](https://github.com/Abbie5/oldpotions/issues/4)

**Comment by Sjouwer** [comment]
Taking a very quick look I think it might have to do with Old Potions not taking into account that there could be more than the default amount of Status Effects

**Comment by Sjouwer** [comment]
I'm going to close this one since it's not something that can be fixed on my end
