### ISSUE TITLE
On a LAN world, others must install this mod

### ISSUE THREAD

**Issue by bernzrdo** [Sjouwer/gamma-utils#22]
The mod is listed as "Client" on Modrinth and doesn't seem to have any server features. Dispite that, when someone tried to join my LAN world, they had to install this mod.

**Comment by Sjouwer** [comment]
Thank you for the report, I suspect I know what's causing that. However I won't have time this week to look at it, I'll try to fix it next week

**Comment by Sjouwer** [comment]
Issue should be fixed now, a new release has been published for 1.19.4 and 1.20/1.20.1
