### ISSUE TITLE
Random Night Vision

### ISSUE THREAD

**Issue by Ventixity** [Sjouwer/gamma-utils#24]
I'm pretty sure that it is because of this mod, but I just have a night vision effect and I cannot turn it off.

**Comment by Sjouwer** [comment]
There's a keybind for toggling the Night Vision effect, by default it's H
You can also change the keybind in the default minecraft keybindings menu

![image](https://github.com/Sjouwer/gamma-utils/assets/84018133/4334e162-9d56-4fc0-ba7b-1afc31eba291)

**Comment by Sjouwer** [comment]
Did you manage to turn off Night Vision or did the keybind not work?

**Comment by Ventixity** [comment]
Yes, sorry. I turned it off. I didn't see the keybind the first time. Sorry for the trouble.

**Comment by Sjouwer** [comment]
That's good to hear, thank you for the update.
I'll close this issue now then
