### ISSUE TITLE
Performance Issues with new update 1.7.16

### ISSUE THREAD

**Issue by Albaraa-PC** [Sjouwer/gamma-utils#27]
It started when i noticed strange drop frames although i have good PC and mods that increase the frames, i tried to replace the new update with old one 1.7.15 and the game started normally.

My PC:
i5 8600
RTX 3050

**Comment by Sjouwer** [comment]
The only difference between 1.7.15 and 1.7.16 is the addition of extra languages, those don't have any impact on performance. It probably was something else, maybe a background process that was running on your pc at that time
