### ISSUE TITLE
Gamma stuck at 1500% even after removing mod

### ISSUE THREAD

**Issue by omo50** [Sjouwer/gamma-utils#29]
Hello! Ive been using a heavily modded modpack ive made, and i love the mod, but my gamma is forever stuck at 1500%
I cant lower it, it wont change, it could maybe be a mod conflict (as my modpack does have 400+ mods) but id feel id ask for some help here anyway

info about the bug:

Gamma is completely jammed at about 1500% and will not change even after deleting the mod from the modpack and the mods folder

this allows oceans to be very easy to see through, caves to not be dark at all

game info:

Fabric 0.14.22
1.20.1
442 mods (sorry)

**Comment by Sjouwer** [comment]
hmm sounds to me like you've got another mod that changes the gamma. Can you post the full mod list?

**Comment by omo50** [comment]
yeah, give me just a couple of minutes

**Comment by omo50** [comment]
oh my gosh, im so sorry i got caught up in stuff all day

i figured the issue out, sorry for bothering you genuienly
love your mod, have a great day, and again sorry!!
