### ISSUE TITLE
Game crashes when I left click

### ISSUE THREAD

**Issue by sarreos** [Sjouwer/gamma-utils#32]
[crash-2024-04-10_22.13.54-server.txt](https://github.com/Sjouwer/gamma-utils/files/14937334/crash-2024-04-10_22.13.54-server.txt)

**Comment by Sjouwer** [comment]
The version of Gamma Utils that you're using only supports Minecraft 1.20.2
Please use this version instead: https://modrinth.com/mod/gamma-utils/version/1.7.19

**Comment by sarreos** [comment]
Looks like it was Prism Launcher's fault, it didn't remove the outdated mod when updating the modpack. Thanks for the fast response!

**Comment by Sjouwer** [comment]
You're welcome!
