### ISSUE TITLE
Does not work with BSL shaders

### ISSUE THREAD

**Issue by TheGentleTurtle** [Sjouwer/gamma-utils#33]
Hello. I recently just installed the gamma ultis mod and was disgruntled at the fact that it does not work with BSL shaders. I was wondering if there was any way to fix this and or if I am doing something wrong. If there are other shaders similar to BSL that work with ultis I will switch shaders if necessary.

**Fabric loader**
**Mods installed:**

- Cloth Config API
- Fabric API
- Gamma Ultis
- Mod Menu
- Reeses SOdium Options
- Sodium Extra
- Sodium (Fabric)
- Iris

Best,
TheMagicianGamer

**Comment by Sjouwer** [comment]
The gamma toggle doesn't work with any shader as far as I know. However, have you tried using the Night Vision toggle instead? That one should work with most shaders. (Default keybind is H)

**Comment by Sjouwer** [comment]
Just tested it, the Night Vision toggle from Gamma Utils works great with BSL:
![2024-05-13_23 00 27](https://github.com/Sjouwer/gamma-utils/assets/84018133/7ffa4894-eb80-4d1b-856e-84890201bf9a)

Closing this now
