### ISSUE TITLE
Gamma resets after changing dimensions

### ISSUE THREAD

**Issue by Brewer5700** [Sjouwer/gamma-utils#34]
Every time I go through a nether portal, an end portal, or the end return portal, my gamma seems to turn off. Is this intended? If so, is there a way to disable this?

**Comment by Sjouwer** [comment]
That's not intended, which Minecraft version do you play on and which Gamma Utils version do you use?

**Comment by Brewer5700** [comment]
I'm using Gamma Utils version 1.7.19 on mc version 1.20.4

**Comment by Sjouwer** [comment]
I was unable to reproduce the issue with this basic setup:
- Minecraft: 1.20.4
- Fabric Loader: 0.15.11
- Gamma Utils: 1.7.19
- Fabric API: 0.97.0
- Cloth Config 13.0.121

Which other mods are you using?

**Comment by Brewer5700** [comment]
Yea, after I made this issue, I had a thought that it was one of the other mods I was using, as I have quite a few

My full mods list will be at the end of this post, but narrowing down the mods one by one, I was able to figure out that the issue seems to arise when using the following mods:

- Fabric API 0.97
- Cloth Config 13.0.121
- Malilib 0.18.1
- Tweakfork 1.3.0

The issue doesn't seem to arise using the normal Tweakeroo mod however.

And here's my full mod list
- AutoTotem 1.0.4
- Better Command Block UI 0.5.1
- CalcMod 1.3.1
- Carpet Extra 1.4.128
- Carpet TIS Addition 1.58.0
- Cloth Config 13.0.121
- Entity Culling 1.6.4
- Fabric API 0.96.11
- Fabric Carpet 1.4.128
- Fabric Language Kotlin 1.10.19
- Fabrishot 1.12.1
- Freecam Fabric 1.2.3
- Gamma Utils 1.7.19
- Indium 1.0.30
- InventoryProfilesNext 1.10.10
- Iris 1.6.17
- Lambdynamiclights 2.3.4
- libIPN 4.0.2
- Litematica 0.17.2
- Litematica Printer 3.2.1
- Lithium 0.12.1
- Magiclib 0.18.1
- Malilib 0.18.1
- MasaGadget 3.2.334
- Minihud 0.30.2
- Modelfix 1.14
- Modmenu 9.0.0
- NBT Auto Complete 1.2.1
- Replay Mod 2.6.15
- Shulker Box Tooltip 4.0.8
- Sodium Extra 0.5.4
- Sodium 0.5.8
- Syncmatica 0.3.11
- Tweakermore 3.17.0
- Tweakeroo 0.19.2
- Tweakfork 1.3.0
- WorldEdit Mod 7.3.0
- Yet Another Config Lib 3.3.2
- Zoomify 2.13.2

**Comment by Sjouwer** [comment]
Sorry for the late reply, but I looked into the code and it looks like it Tweakfork sets the gamma value that is set in its config every world load. Not much I can do about that. If all you care about is always having the same gamma value and don't need the other functionalities of Gamma Utils then you could just set the gamma in Tweakfork and remove Gamma Utils

**Comment by Brewer5700** [comment]
Ah okay, I had no idea Tweakfork had the option to change Gamma, thanks a lot!
