### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [Sjouwer/gamma-utils#36]
[latest.log](https://github.com/user-attachments/files/15524423/latest.log)
1
[crash-2024-06-02_14.43.44-client.txt](https://github.com/user-attachments/files/15524424/crash-2024-06-02_14.43.44-client.txt)

**Comment by Sjouwer** [comment]
Gamma Utils and Boosted Brightness don't work together, they mixin into the same place. Only use one of the 2
