### ISSUE TITLE
Crash when going onto Nether ceiling

### ISSUE THREAD

**Issue by trsdi** [Sjouwer/gamma-utils#38]
Hi! Really weird bug, I'm not sure which mod is causing it but I think it's this one. I crash right as I reach the top of my ladder leading to the nether roof. I've crashed two times in a few hours this same way. When I load back in, everything is fine again so I'm not sure what's happening

[crash-2024-06-26_20.55.15-server.txt](https://github.com/user-attachments/files/16008449/crash-2024-06-26_20.55.15-server.txt)
[crash-2024-06-26_22.04.52-server.txt](https://github.com/user-attachments/files/16008452/crash-2024-06-26_22.04.52-server.txt)

[modlist.txt](https://github.com/user-attachments/files/16008525/modlist.txt)

**Comment by Sjouwer** [comment]
Hi, sorry for the late reply, however it doesn't look like the crash is related to this mod. The crash you posted is a server crash, while this mod is fully client side. There is also nothing in the crash file itself that would indicate this mod is the cause of it.
