### ISSUE TITLE
Further Development

### ISSUE THREAD

**Issue by GraysonHackett** [Sjouwer/gamma-utils#41]
After digging through the code for a little, I see the perm night vision effect comes down to the .NIGHT_VISION ... could this be done for any effect in the game as well? Might be cool to implement different options with different keybinds

**Comment by Sjouwer** [comment]
Night Vision and I believe Darkness are the only effects that are fully client side, all other effects would require modding the server as well. However, even if it was possible to add other effects to a keybind, I still wouldn't add them. They wouldn't be relevant to this mod and would also cross the line of what's considered cheating. Most mc communites and servers are fine with fullbright mods, I can garantee you this won't be the case for other effects.
