### ISSUE TITLE
Dynamic gamma

### ISSUE THREAD

**Issue by MirokaSult** [Sjouwer/gamma-utils#46]
The new dynamic gamma feature is sooooo cool and useful, but I like to use gamma when I'm in cave and turn it off when outside at night (it has its own vibe for me), so is it possible to make an option for that feature to ignore the night time somehow? Maybe check if player has any blocks above them or check sky light level? I would really appreciate if you could do so. Thanks for such a great mod!

**Comment by Sjouwer** [comment]
Thank you for the suggestion, I like the idea and will add it soon

**Comment by Sjouwer** [comment]
The latest versions that just released have an option to override the sky brightness. Set this to 100 and you'll have no dynamic lighting when outside under sky light.
