### ISSUE TITLE
Gamma keys incorrectly execute when other modifier keys are held

### ISSUE THREAD

**Issue by BrailleBennett** [Sjouwer/gamma-utils#54]
When you hold alt and press g or h the gamma function executes even though the keybind shouldn't include modifier keys.

**Comment by Sjouwer** [comment]
The keybinds are added using Fabric API, it's a limitation of theirs. I could fix it by writing my own keybind api, however I do not have any plans to do so. Alternatively it can also be resolved by using mods like [amecs](https://modrinth.com/mod/amecs).
