### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by Icarus-MC** [Sjouwer/gamma-utils#59]
My goal when using this mod is to make the game/lighting engine behave like pre 1.19 when you could enter the .txt file and set your gamma to whatever you wanted. My preferred level is 500 gamma. Previous versions of the mod worked as expected, but now on MC version 1.21.3 everything is different. Even when "disabled" the mod effects the lighting engine so that 100% gamma is fullbright. I despise fullbright: hence my downloading of this mod in the first place- making the mod irrelevant.  

Also, something broke while I wasn't looking because there is no difference between 100 gamma and anything above it. T

In older versions: 500 gamma was the sweet-spot between visibility and ability to tell the light level of a block. Now, Everything is fullbright all the time and there's nothing I could figure out to fix it. The closest I can get to the desired result is setting the gamma to 0 while having the mod installed. Please help!

The following screenshots are different gamma levels within the mod; the last being 0: 
![2024-12-04_02 02 58](https://github.com/user-attachments/assets/173d60c8-bde7-4d99-a9d2-2076411bd069)
![2024-12-04_02 03 01](https://github.com/user-attachments/assets/59d1c287-4d5b-4f5f-b19b-0d95f09a73f2)
![2024-12-04_02 03 21](https://github.com/user-attachments/assets/86cfa204-e150-4669-be3b-a0abbfdef2b4)

these screenshots are unmodded 0 gamma and 100 gamma respectively:
![2024-12-04_02 09 09](https://github.com/user-attachments/assets/f4a3c292-4261-4850-994c-87a09c5217fd)
![2024-12-04_02 09 19](https://github.com/user-attachments/assets/c6a5d217-c0df-400e-874c-272833b39d92)

**Comment by Sjouwer** [comment]
Hey, are you sure there's no other mod or texture pack loaded that causes this? Try testing with only Gamma Utils and its dependencies without any other mod/texture pack. Also make sure you get Gamma Utils either from Modrinth or CurseForge

**Comment by Icarus-MC** [comment]
> Hey, are you sure there's no other mod or texture pack loaded that causes this? Try testing with only Gamma Utils and its dependencies without any other mod/texture pack. Also make sure you get Gamma Utils either from Modrinth or CurseForge

I've isolated the mod (with fabric API and cloth config) which is what you see in the screenshots apart from the other two at the bottom which are mod free. Currently also using vs 2.2.2  (current patch) of the mod. no differences with resource packs and without.  

Think it could be an issue with my java version?

here is current mod list:
![image](https://github.com/user-attachments/assets/0a776a54-19e4-4c4d-9d2b-bfd1d63a5419)

**Comment by Sjouwer** [comment]
Ah, I think I know what's going on, you probably enabled Night Vision by accident.
The Night Vision toggle key is H by default.

**Comment by Icarus-MC** [comment]
well..... I feel quite silly. Tsym for the help!!!!! ❤️

still, it looks different to what I remember for 1.20.1 (last time i played) Maybe the lighting engine has been updated since? I'll figure it out. Thanks!!!

**Comment by Sjouwer** [comment]
Awesome, you're very welcome, great to hear that solved it!

Hmm, I don't beleive there have been any lighting engine changes, though I could very well be wrong with that.
Hopefully you'll figure some settings out that work for you, the mod should provide plenty of adjustability for that :)

In any case, I'll be closing this now.
