### ISSUE TITLE
Using gamma utils permanently destroys gamma.

### ISSUE THREAD

**Issue by Konglomneshued** [Sjouwer/gamma-utils#6]
I had gamma utils installed but hadn't used it until now.  I used it in a cave and it worked fine but everything else is screwed up, permanently.  I went outside and some places are permanently bright or permanently dark.

I have several perfomance mods installed including: starlight, Lamb Dynamic lights, lithium, sodium, etc.

Screenshots
https://imgur.com/a/7DT3ZU9

**Comment by Sjouwer** [comment]
All this mod changes is the gamma value found in the minecraft options.
By default minecraft allows you to use 0 - 1 (0 - 100%), but my mod removes that limit.
It doesn't touch anything else and it's impossible for this mod to break the lighting like that.
~~I suspect Starlight is probably the one that actually caused the issue you're experiencing.
That mod rewrites the complete light engine, something I don't touch at all.~~

**Comment by Sjouwer** [comment]
From someone else that has the same type of issue I found out the actual mod that's causing the issue is Colormatic.
https://github.com/kvverti/colormatic/issues/77
Hopefully this will be able to help you a bit.
